#!/usr/bin/python2.7

#move this file to .git/hooks
import os
import os.path

files = []
currentDirPath = "files/Systems"

for dirpath, dirnames, filenames in os.walk("files"):
    for filename in [f for f in filenames if f.endswith(".md")]:
        if not(files):
            currentDirPath = dirpath
        if currentDirPath != dirpath:
            currentDirPath = dirpath
            files.append("")
        files.append(os.path.join(dirpath, filename))

fileLog = open("files.txt", "w")

for filePath in files:
    fileLog.write(filePath + "\n")

fileLog.close()
os.system("git add --all")
